<?php

function temperaturemeter_menu() {
  $items['temperaturemeter'] = array(
    'title' => 'Temperature meter',
    'page callback' => 'temperaturemeter_custom_page',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );
  $items['temperaturemeter/get/dispositivosPerEmpresa'] = array(
    'page callback' => 'get_dispositivos_ajax',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );  
  return $items;
}

function get_dispositivos_ajax(){
  if(isset( $_POST["idEmpresa"])):
    $idEmpresa = $_POST["idEmpresa"];
  endif;
  
  $temperature = get_dispositivos($idEmpresa);
  drupal_json_output($temperature);
}

function get_temperatura_per_dispositivo($idDispositivo, $idEmpresa){
  $query = db_select('temperaturas', 't');
  $query->condition('t.id_dispositivo', $idDispositivo, '=');
  $query->condition('t.id_empresa', $idEmpresa, '=');
  $query->range(0,1);
  $query->orderBy('t.fecha', 'DESC');
  $query->fields('t');

  $results = $query->execute();

  foreach($results as $result){
    $temperature = array(
      'id' => $result->id, 
      'fecha' => $result->fecha, 
      'sensor1' => $result->sensor1, 
      'color1' => sensorColor($result->sensor1), 
      'sensor2' => $result->sensor2, 
      'color2' => sensorColor($result->sensor2), 
      'sensor3' => $result->sensor3, 
      'color3' => sensorColor($result->sensor3), 
      'sensor4' => $result->sensor4, 
      'color4' => sensorColor($result->sensor4), 
      'id' => $result->id,
    );
  }
  return $temperature;
}

function get_dispositivos($idEmpresa){
  db_set_active('temperature');
  $query = db_select('dispositivos', 'd');
  $query->condition('d.empresa_id', $idEmpresa, '=');
  $query->fields('d');

  $results = $query->execute();

  foreach($results as $result){
    $temperatura = get_temperatura_per_dispositivo($result->dispositivo_id, $result->empresa_id);
    $temperatura["nombre_dispositivo"] = $result->nombre; 
    $dispositivos[] = array(
      'temperatura' => $temperatura,
    );
  }
  
  db_set_active('default');
  return $dispositivos;  
}

function sensorColor($sensorTemperature){
  if($sensorTemperature < 33){
    $color = 'temperature_color_green';
  }elseif($sensorTemperature > 33 && $sensorTemperature < 66){
    $color = 'temperature_color_yellow';
  }else{
    $color = 'temperature_color_red';
  }
  return $color;
}

function get_empresas(){
  db_set_active('temperature');

  $query = db_select('empresas', 'e');
  $query->fields('e', array('nombre', 'empresa_id'));
  $query->orderBy('e.nombre', 'DESC');

  $result = $query->execute()->fetchAll();

  db_set_active('default');
  return $result;
}

function temperaturemeter_preprocess_page(&$variables){
  if($variables["theme_hook_suggestions"][0] == 'page__temperaturemeter'):
    global $base_url;
    drupal_add_js(array('temperaturemeterHelpers' => array('baseUrl' => $base_url,  'url' => 'temperaturemeter')), array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'temperaturemeter') . '/js/temperaturemeter.get_temperature.js');
  endif;
}

function temperaturemeter_custom_page(){
  $empresas = get_empresas();
  return theme('temperaturemeter', array('empresas' => $empresas));
}

function temperaturemeter_theme() {
  return array(
    'temperaturemeter' => array(
      'render element' => 'elements',
      'template' => drupal_get_path('theme', variable_get('theme_default', NULL)) . '/templates/pages/temperaturemeter',
      'variables' => array(
        'empresas' => NULL,
      ),          
    ),    
  );
} 
